### ISSUE TITLE
Junk learning doesn't seem to work

### ISSUE THREAD

**Issue by zalaare** [flathub/org.gnome.Evolution#10]
`flatpak info org.gnome.Evolution`
```
Evolution - Manage your email, contacts and schedule

          ID: org.gnome.Evolution
         Ref: app/org.gnome.Evolution/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.32.1
     License: GPL-2.0+ and GFDL-1.3
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 36.7 MB
     Runtime: org.gnome.Platform/x86_64/3.32
         Sdk: org.gnome.Sdk/x86_64/3.32

      Commit: 24ece566b9ea4b6d86d921c498e2ad17811d14f827d67dda1b16cf3a4fa80697
      Parent: 328983ddece37467ba26aec640f181d5b75e7030de372db238e37445585c627d
     Subject: Updating to 3.32.1 (5b5743fd)
        Date: 2019-04-09 11:40:23 +0000
```

I'm not sure that Evolution isn't working as intended while running as a flatpak app, however I cannot get org.gnome.Evolution to learn how to flag junk mail as junk.  I've been clicking "Mark the selected messages as junk" for awhile now but nothing seems to end up in Junk that I didn't put there.

Is there more to the configuration that I'm missing?  I found
```
[📦 org.gnome.Evolution ~]$ find / -name '*bogo*'
/app/lib/evolution/modules/module-bogofilter.so
/app/share/glib-2.0/schemas/org.gnome.evolution.bogofilter.gschema.xml
/app/share/metainfo/org.gnome.Evolution-bogofilter.metainfo.xml
```
Please advise as I'm currently on Silverblue 30 (atomic OS) and flatpaks are the bread-and-butter for this OS.  As I said, there might not be anything wrong, but if this is the case, then the learning process is brutal. :D

Here are the pertinent settings:
![alt text](https://zalaare.freeddns.org/screenshots/gnome/20190501-Evolution.Plugins.png "Enabled Plugins")
![alt text](https://zalaare.freeddns.org/screenshots/gnome/20190501-Evolution.Preferences.Junk.png "Current Junk Preferences")
![alt text](https://zalaare.freeddns.org/screenshots/gnome/20190501-Evolution.Account.Receiving.Options.png "Specific Account Receiving Options")

**Comment by Sesivany** [comment]
I suppose this is a problem of missing spam filter in the flatpak. Neither bogofilter nor spamassassin are present in the flatpak and Evolution cannot use reach them from within the sandbox if they're running on the host. I'll discuss with the upstream developer if there is anything we can do about it.

**Comment by zalaare** [comment]
I didn't realize that bogofilter generally runs as a service on the host.  I simply assumed, since /app/lib/evolution/modules/module-bogofilter.so existed within the flatpak, it should work.  Your explanation makes sense!  Hopefully upstream has some ideas.

**Comment by Sesivany** [comment]
The latest update (3.32.4) is built with Bogofilter, so it should work now. You can give it a try here: flatpak install https://dl.flathub.org/build-repo/5328/org.gnome.Evolution.flatpakref
Or it will be propagated to the stable repo during today.

**Comment by zalaare** [comment]
I know this is closed, however it should be noted, that this change made no difference as far as I can see.  If bogofilter needs to be running as a daemon or something on the host, then this probably won't ever be resolved as things stand.  Installing bogofilter (at least on Silverblue) results in a full Evolution Suite being installed negating any need for a flatpak.

**Comment by Sesivany** [comment]
It does work for me. I mark a message as junk it's moved to Junk, I mark it as not junk and it's moved back to the original folder.

**Comment by zalaare** [comment]
Evolution has always moved marked junk to junk and not junk back out.  This issue is entirely about junk learning (also known as adaptive junk filtering).  New spam mail messages coming into Evolution will not be flagged no matter how much junk you mark as junk. Evolution is not "learning".  Bogofilter is the component that you teach via training.  This is normally done in Evolution's case in the background as you mark mail as junk or unmark false positives.

**Comment by Sesivany** [comment]
Can you please check if the bogofilter database really doesn't get updated after the actions? It's located in .var/app/org.gnome.Evolution/data/bogofilter/wordlist.db.

**Comment by zalaare** [comment]
I've marked and unmarked about 20 messages to test:
The bogofilter directory is never created.
```
ls ~/.var/app/org.gnome.Evolution/data
applications  camel_certs  evolution  recently-used.xbel  webkitgtk
```

**Comment by Sesivany** [comment]
You're right. We had a bug in the Flathub manifest. It should be fixed now. You can try it immediately: flatpak install https://dl.flathub.org/build-repo/6647/org.gnome.Evolution.flatpakref
Or wait for an update in Flathub that should land during today.

**Comment by zalaare** [comment]
Bogofilter folder and wordlist created as soon as the new Evolution started.  I think it is probably good-2-go now.  Thanks!

**Comment by monperrus** [comment]
Hi, I'm running Evolution from flathub `3.42.3 (flatpak git) `.

In Preferences >> Plugins, I don't see the bogofilter plugin for activation.

Any idea on how to activate bogofilter on flatpak Evolution?

Thanks!

**Comment by mcrha** [comment]
> Any idea on how to activate bogofilter on flatpak Evolution?

The bogofilter is built ad bundled:<br>
https://github.com/flathub/org.gnome.Evolution/blob/master/org.gnome.Evolution.json#L282

When Evolution has only one Junk plugin installed, it doesn't offer to pick from one of them. The Bogofilter has an option, shown as:
```
   Bogofilter Options
      [x] Convert mesasge text to Unicode
```
at the end of the Edit->Preferences->Mail Preferences->Junk tab, which I do see in the 3.42.3 release Flatpak build from here.

**Comment by monperrus** [comment]
Thanks.

Do you mean that bogofilter is the plugin used by default? And that even if we don't see it in the plugin list, it is actually there?

**Comment by mcrha** [comment]
Yes ans yes. Neither the bogofilter, nor spamassassin, plugin is shown in the Plugins, it's only in the Edit->Preferences->Mail Preferences->Junk tab.

**Comment by monperrus** [comment]
Very good to know.

Now, I want to port my old junk db to flatpak.

That is:

    mv $HOME/.bogofilter/wordlist.db $HOME/.var/app/org.gnome.Evolution/data/bogofilter/wordlist.db

Sounds reasonable?

**Comment by mcrha** [comment]
> Sounds reasonable?

Probably. I do not know bogofilter internals enough to know for sure, but it's something I would do too. The only problem could be if they changed the .db format.
