### ISSUE TITLE
When will this be updated to 3.32.2?

### ISSUE THREAD

**Issue by AxelMKlein** [flathub/org.gnome.Evolution#11]
Sorry for opening an issue for this question, but I did not figure out any other way. So

1. Is there a schedule for updating Evolution to 3.32.2?
2. How could I ask this question "in the right way"?

Thanks in advance.

**Comment by Sesivany** [comment]
I was planning to bundle it with some other changes which I haven't found time for. I'll update the app on Mon with or without the changes. Sorry for the delay.

**Comment by AxelMKlein** [comment]
No problem.
I just want to check out whether PGP-signing works now.
Thanks a lot!

**Comment by Sesivany** [comment]
It should be now available in Flathub.
