### ISSUE TITLE
PGP-Signing gives 'pinentry' error.

### ISSUE THREAD

**Issue by AxelMKlein** [flathub/org.gnome.Evolution#12]
Trying to sign a message with a PGP-Key gives these errors:
In German:
- gpg: Schreiben nach '-', 
- gpg: Beglaubigung fehlgeschlagen: Kein Pinentry, 
- gpg: signing failed: Kein Pinentry. 

In English: 
- gpg: Writing after '-', 
- gpg: Authentication not successful: No pin-entry, 
- gpg: signing failed: No pin-entry. 

mcrha thinks it might be solvable by including 'pinentry' or by disabling it.

**Comment by AlexGitReid** [comment]
I am also experiencing this issue. I am able to use keys with no passphrase to sign and decrypt mail, but when using a key with a passphrase I get the above error.

**Comment by idnovic** [comment]
I have the same error. On an sidenote s/mime works.

Just /usr/bin/pinentry-gnome3 is not loaded from the system

**Comment by AxelMKlein** [comment]
Is there a solution on the horizon?

**Comment by agates** [comment]
Can someone pull the fix from the upstream repo?

**Comment by Sesivany** [comment]
The lastest update (3.32.4) is built with pinentry, you can give it a try: flatpak install https://dl.flathub.org/build-repo/5328/org.gnome.Evolution.flatpakref
Or it will be propagated to the stable repo during today.

**Comment by agates** [comment]
Confirmed fixed :)

**Comment by Nycticorax** [comment]
Sorry but still having this: 
```
Detailed error: Output from gpg2:
gpg: écriture de « - »
gpg: échec de la signature : Pas de pinentry
gpg: signing failed: Pas de pinentry
```

**Comment by Cogitri** [comment]
@Nycticorax fwiw that's not Evolution from Flathub, but Evolution from Fedora. It also doesn't work with Fedora's Evolution, but does with flathub's version. Try the following:

```
flatpak uninstall org.gnome.Evolution
flatpak install flathub org.gnome.Evolution
```

**Comment by Nycticorax** [comment]
> @Nycticorax fwiw that's not Evolution from Flathub, but Evolution from Fedora. It also doesn't work with Fedora's Evolution, but does with flathub's version. Try the following:
> 
> ```
> flatpak uninstall org.gnome.Evolution
> flatpak install flathub org.gnome.Evolution
> ```

I see, thanks I switched to the flathub version and it works OK!

**Comment by Cogitri** [comment]
It should be fixed in Fedora's version soon too, see https://bugzilla.redhat.com/show_bug.cgi?id=1900395 for the Fedora bug report
