### ISSUE TITLE
[Evolution 3.50.1] Can't import contact certificates

### ISSUE THREAD

**Issue by adelanchy** [flathub/org.gnome.Evolution#149]
Hello,

I encouter a problem with flatpak and Evolution with Ubuntu 22.04.
I installed the latest version of Evolution available (3.50.1) and I have troubles with the import of contact certificate.

When I start Evolution I go to preferences , then certificates then contact certificates.
![IMG_0001](https://github.com/flathub/org.gnome.Evolution/assets/151510975/6c9072f7-595d-4ec6-b538-97fb887199c3)

I import the p7b file with all contacts.
![IMG_0002](https://github.com/flathub/org.gnome.Evolution/assets/151510975/a54ac862-6d04-434f-a03b-77cd72089cf6)
![IMG_0003](https://github.com/flathub/org.gnome.Evolution/assets/151510975/478bb253-478e-4937-ba98-9784aa669fbe)

It works but when I restart Evolution the list is empty !?
![IMG_0005](https://github.com/flathub/org.gnome.Evolution/assets/151510975/eaabd272-9a68-4aa9-9a57-38f6959ba080)

Is there a way to generate and provide logs ? is this related to flathub or Ubuntu (since I don't have the problem on Ubuntu 20.04) ?

**Comment by Sesivany** [comment]
Hi, we think we've been able to reproduce it. Evolution saves it into ~/.pki, but apparently if the directory doesn't exist, the flatpak portal doesn't give Evolution an access to it and Evolution cannot create it because it doesn't have rights to do it.
Try to manually create a ".pki" directory in your home.

**Comment by adelanchy** [comment]
Hello, 

Thanks , we give a try and it works.
