### ISSUE TITLE
Help with Smartcards

### ISSUE THREAD

**Issue by mathomp4** [flathub/org.gnome.Evolution#16]
All,

First, let me preface this by saying I'm a very big newbie with regards to Flatpak. I learned about it yesterday, so this might be a non-issue, but my searched didn't reveal anything. Still, here we go...

My work (NASA) recently moved to use mandatory PIV card authentication for email through O365 and Oauth2. As my main workstation is a Linux box, I only have a few paths. One is to use Outlook on the web which, not a fan, but it works because Chrome and Firefox authenticate well.

The second is to use Thunderbird with Davmail which is what I currently use. It's usable to a point but quite slow and not perfect.

The third path was to use Evolution with its EWS support, huzzah! Problem, I'm on an older OS (CentOS 7) so my built-in Evolution is 3.28. Now the O365 people say this is new enough to support EWS/O365/Oauth2 whatever and I think Evolution does, but the problem occurs when the little web browser popup opens for me to validate my PIV card. A search around the web seemed to say to me that the WebKit minibrowser (?) that Evolution pops up didn't have the right support for web authentication of smart cards until GNOME 3.34 (I think my deep dive started here: https://bugs.webkit.org/show_bug.cgi?id=164509). Since I can do it in Firefox and Chrome, I'm assuming that Evolution doesn't use them to render webpages.

So I followed the [Evolution Flatpak instructions](https://wiki.gnome.org/Apps/Evolution/Flatpak) and (surprisingly given how old my Flatpak is, 1.0.2) it built! Unfortunately, it still didn't want to see my smart card. I even tried building Gnome 3.34 and changing the json to use 3.34 (before I saw #14), no difference.

So, outside of not being able to use 3.34 (see #14), I was wondering: 

  Would there be anything more needed for smartcard support?

A troll around Google with "smart card" and "flatpak" seemed to point to the `opensc` branch of the Thunderbird flatpak where [the .json was recently updated](https://github.com/flathub/org.mozilla.Thunderbird/blob/opensc/org.mozilla.Thunderbird.json) to add smart card support (using `pcsc-lite` and not `opensc`...not sure why). I don't see anything similar in the Evolution json, so would it need something similar to see my smart card reader?

**Comment by TingPing** [comment]
>  A search around the web seemed to say to me that the WebKit minibrowser (?) that Evolution pops up didn't have the right support for web authentication of smart cards until GNOME 3.34 (I think my deep dive started here: bugs.webkit.org/show_bug.cgi?id=164509). Since I can do it in Firefox and Chrome, I'm assuming that Evolution doesn't use them to render webpages.

Hi, this is completely off-topic for this package but I am implementing smartcard support in WebKit, it will not exist until WebKitGTK 2.28 in ~6 months. https://bugs.webkit.org/show_bug.cgi?id=200805

**Comment by TingPing** [comment]
> A troll around Google with "smart card" and "flatpak" seemed to point to the opensc branch of the Thunderbird flatpak where the .json was recently updated  to add smart card support (using pcsc-lite and not opensc...not sure why). I don't see anything similar in the Evolution json, so would it need something similar to see my smart card reader?

Out of the box opensc can't work, there likely needs to be some safe interface to the host for that. Maybe `--device=all` just happens to work *shrug*.

**Comment by fbruetting** [comment]
Does this help?
flathub/org.mozilla.Thunderbird/issues/51

**Comment by Sesivany** [comment]
If you find a working solution, let me know. We have neither a smartcard reader, not a smart card. So it's not something we can test.

**Comment by mathomp4** [comment]
All, I keep trying every so often, but I still have never succeeded with this. Flatpak evolution can't see the smartcard still. If anyone else figures it out, please comment here.

**Comment by TingPing** [comment]
Please don't bump this unless you are working on a solution. Yes it doesn't work that is what this issue is about.

**Comment by tkuraku** [comment]
This is something that needs to be implemented as a flatpak portal. I don't think it is application specific. https://github.com/flatpak/flatpak/issues/3076

**Comment by Talisker69** [comment]
Hi All, Happy new year,
I understood that now flatpak support smart card so I installed the lastest version of Thunderbird. it's works but I loose my access to my security token. I usually use Opensc and use the Opensc-pkcs11.so as module in Thunderbird (and Firefox, Veracrypt, ..). Now with flatpak witch module I should use ? I saw that pcsc is supported but it's a lowlevel stack so I don't know what todo. I'm using the latest version of Thunderbird and Flatpak. Is someone have a configuration that works with a Thunderbird and a smartcard ?

**Comment by Sesivany** [comment]
We've come up with some changes in the sandbox that should allow smartcard support, please let us know if it's working for you.

**Comment by mathomp4** [comment]
> We've come up with some changes in the sandbox that should allow smartcard support, please let us know if it's working for you.

Might be a while for me. My poor Linux box is at my work office where I currently am not (stupid virus). But hopefully someone else can test this out, though I definitely will when I can be back!

**Comment by fbruetting** [comment]
I just updated to v3.38.4. When I go into my account's security settings, I sadly don't see my smartcard appearing in the selection list.  Is there some step missing?

**Comment by Sesivany** [comment]
Basically what we did was enabling the smartcard access in the sandbox just like Thunderbird does that:
https://gitlab.gnome.org/GNOME/evolution/-/commit/e2a6ef82ae5b7c3f56182f0d3cdc0c60995011b3#905423869df6a841b309925dbece66c674583a69
I'll report it back to the main dev, I can't really test it myself since I don't have a smartcard.

**Comment by fbruetting** [comment]
I sadly was not able to find documentation on this.

In Firefox it used to be necessary to manually load the library `opencs-pkcs11.so` as a crypto module - which happened automatically now. I don't know of something like this is necessary for Evolution, nor do I see any option to do so. 🤔

-------- Original-Nachricht --------

**Comment by Sesivany** [comment]
We did what we were asked to do on the Evolution and its flatpak side. Although I cannot test it myself, AFAIK the smartcard support should mostly work, the rest really depends on Flatpak and XDG portals, thus I'm closing this report.
