### ISSUE TITLE
Can not start address book

### ISSUE THREAD

**Issue by adds68** [flathub/org.gnome.Evolution#17]
Hi all,

Since updating to the latest flatpak my address fails to start:

`This address book cannot be opened.  This either means that an incorrect URI was entered, or the server is unreachable.`

`Detailed error message: Unable to connect to “Codethink”: The name org.gnome.Evolution.org.gnome.evolution.dataserver.AddressBook10 was not provided by any .service files`

Any idea what could be the issue here?

**Comment by Sesivany** [comment]
Are you still experiencing this problem?

Do you get any error messages if you run Evolution from the command line (flatpak run org.gnome.Evolution)?

**Comment by Sesivany** [comment]
No follow-up from the reporter, closing the ticket.
