### ISSUE TITLE
EWS connection doesn’t work

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.gnome.Evolution#18]
* v3.34

When I enter my credentials (which work in the RPM package), I get the following error message:

`GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`

Is some portal missing here? Or could that be due to my old `flatpak v1.0.7`?

**Comment by Sesivany** [comment]
Hi, try to list all processes that have 'evolution' in the name (ps ax | grep evolution), kill them and then start the flatpak again.

**Comment by ovari** [comment]
Where does one find and install `evolution-ews` that works with `Evolution (flatpak)`?

Linux Mint's Software Manager has:
Package: evolution-ews
Version: 3.28.5-0ubuntu0.18.04.1

Thank you

Linux Mint 19.2 Cinnamon 64-bit
Evolution 3.34.2 (flatpak from flathub.org)

**Comment by Sesivany** [comment]
evolution-ews is included in the Evolution flatpak, no need to install it. If you have evolution-ews installed on the host, it doesn't make a difference, Evolution in flatpak can't see it.

**Comment by fbruetting** [comment]
> Hi, try to list all processes that have 'evolution' in the name (ps ax | grep evolution), kill them and then start the flatpak again.

I tried that several times and even restarted my machine – sadly that didn’t work out for me. Do you have other ideas, how I can get some debug information for you?

**Comment by Sesivany** [comment]
What is your environment? I just tested it, signed in an Exchange account in GNOME Online Accounts, opened Evolution and it just loaded mail, calendar... data from the account. No problem.

**Comment by fbruetting** [comment]
I plan to fully update/renew my system in the next days – maybe it’s due to the old `flatpak` version. Will get back to this then!



> What is your environment?

Which information would you need?

**Comment by Sesivany** [comment]
Are you still experiencing this issue?

**Comment by lkocman** [comment]
Hmm on similar topic I can't get EWS/SSO (OKTA) authentication working on my evolution/flatpak  as well ... but I don't see error message described above. Based on what I see (unauthorized app) My best guess is that application has to somehow identify itself differently than the version from rpm and has to be explicitly approved by IT. The version from rpm simply works.

**Comment by mcrha** [comment]
> Hmm on similar topic I can't get EWS/SSO (OKTA) authentication working on my evolution/flatpak as well ... 

I guess you face https://gitlab.gnome.org/GNOME/libsecret/-/issues/62

**Comment by Sesivany** [comment]
> Hmm on similar topic I can't get EWS/SSO (OKTA) authentication working on my evolution/flatpak as well ... but I don't see error message described above. Based on what I see (unauthorized app) My best guess is that application has to somehow identify itself differently than the version from rpm and has to be explicitly approved by IT. The evolution from rpm simply works. Could that be the common rootcause for both issues?

It should be fixed in the latest release, can you please verify if it is for you?

**Comment by fcrozat** [comment]
I can confirm oauth against EWS/SSO (Okta) works fine now cc @lkocman
