### ISSUE TITLE
GPG smartcard (Yubikey) support is broken

### ISSUE THREAD

**Issue by taaem** [flathub/org.gnome.Evolution#19]
Evolution Flatpak is not able to see my Smartcard (Yubikey) and it just asks for the device to be plugged in.

Possibly this can be fixed with: https://github.com/flathub/org.mozilla.Thunderbird/issues/51

**Comment by ispanos** [comment]
Can you try `flatpak run --device=all org.gnome.Evolution` and see if it works?

**Comment by taaem** [comment]
@ispanos Sadly it doesn't work, I get a prompt to insert my smartcard which I do and then nothing happens.

**Comment by taaem** [comment]
I suppose there is also the pcsc-lite program missing, because gpg is using that to contact the smartcard. I have it on the host but according to the linked thunderbird issue you also need it inside the flatpak.

**Comment by Sesivany** [comment]
Duplicate of #16
