### ISSUE TITLE
I cannot login to my google account anymore (oauth2 secret not found)

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.gnome.Evolution#20]
Suddenly my google account stopped working with errors "oauth2 secret not found" and "Unacceptable TLS certificate". I uninstalled evolution, I deleted my ~/.var/app/org.gnome.Evolution directory and tried to add them again. The automatic look up for details of gmail doesn't work and when I add the imap and smtp details myself I get the same error.

Evolution from arch repositories works fine. I also don't see any relevant changes to evolution recently so maybe some runtime update broke it?

**Comment by Sesivany** [comment]
We cannot reproduce this on our machines. The oauth2 secret is stored in the system gnome-keyring, so both the Flatpak and distribution Evolution accesses the same. Maybe some regression in the flatpak runtime (and hence the TLS error)? Try 'flatpak update', updating all flatpak-related packages in your distro and reinstalling Evolution.

**Comment by ThanosApostolou** [comment]
It's working fine now. I don't know why, it doesn't seem like anything changed (at least I didn't do anything different). So I'm closing this.
