### ISSUE TITLE
Somehow provide local help

### ISSUE THREAD

**Issue by stdedos** [flathub/org.gnome.Evolution#21]
_From https://discourse.flathub.org/t/evolution-somehow-provide-help/165/_

For reasons (https://gitlab.gnome.org/GNOME/evolution/issues/804#note_724176 3) and offline viewing, maybe it would be nice if evolution-help is installed/installable somehow.

Can you do it / add instructions for it?

**Comment by Sesivany** [comment]
The update to 3.36 is built with local help now.
