### ISSUE TITLE
Update the runtime from 3.32 (EOL) to 3.36

### ISSUE THREAD

**Issue by taaem** [flathub/org.gnome.Evolution#22]
Hello, with the release of 3.36, 3.32 became EOL and while the Evolution app itself was updated, it seems that the runtime is not.

It would be awesome to also update the runtime so users don't need the 3.32 runtime.

**Comment by Sesivany** [comment]
This is fixed with the latest update, thanks for pointing me to the problem, I thought we were already on 3.34.
