### ISSUE TITLE
Update broke connection to evolution data server

### ISSUE THREAD

**Issue by lightonflux** [flathub/org.gnome.Evolution#25]
OS: Ubuntu 20.04
Evolution (flatpak): 3.36.0
Flatpak: 1.6.2

After the update i rebooted and started Evolution anew. It prompted me with the setup wizard. And i proceeded to enter my account details. After setup was complete Evolution presented the error message:

     The name org.gnome.Evolution.org.gnome.evolution.dataserver.Sources5 was not provided by any .service files

Is the duplication rights? Or is that already the error?

**Comment by Sesivany** [comment]
Do you have the very latest update? We released an update that started using GNOME 3.36 runtime, but there were problems with it, so we switched to 3.34 and release another update next day.

**Comment by lightonflux** [comment]
At the time it was the most recent version. But i just updated and it works again.

Was this an incompatibility with the Platform Runtime?
