### ISSUE TITLE
Can't log in to Google account.

### ISSUE THREAD

**Issue by ispanos** [flathub/org.gnome.Evolution#26]
The native packages works fine, but the Flatpak version fails to Authenticate.

After entering my 2-step-verification code, I allow access via the page that google shows every time you log in using an app, the page flashes to something for less that a second, which looks like a link I have to copy, but I usually cant even take a screenshot. 
After that the `URL:` goes to `none-local://` with a message:
```
Failed to obtain access token from address
"https://www.googleapis.com/oauth2/v3/token": user interaction failed
```
Meanwhile I get both an email and a notification from google that '"GNOME Evolution" has now access to my google account....'
I can only click `cancel` and when I do the application crashes. 
If I open the `Account Edit` and hit `cancel`, Evolution crashes.
```
[yiannis@Biscuit ~ ]$ flatpak run org.gnome.Evolution 

(evolution.bin:27): e-mail-engine-WARNING **: 02:24:10.479: Failed to add service 'Sendmail' (sendmail): No provider available for protocol “sendmail”

(evolution-alarm-notify:33): GLib-GIO-WARNING **: 02:24:10.619: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().

(evolution.bin:27): GLib-GObject-WARNING **: 02:24:25.394: invalid uninstantiatable type '(null)' in cast to 'GTask'

(evolution.bin:27): GLib-GIO-CRITICAL **: 02:24:25.395: g_task_get_task_data: assertion 'G_IS_TASK (task)' failed
/app/bin/evolution: line 32:    27 Segmentation fault      (core dumped) /app/bin/evolution.bin "$@"
```
At first I thought the issue was `gnupg`'s config location:
`export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"`
But when I commented out that, restarted my pc and tried again, it kept happening.
There isn't any `gnupg` folder in `~/.var/app/org.gnome.Evolution/`.

For good measure, I uninstalled `org.gnome.Evolution`, `deleted ~/.var/app/org.gnome.Evolution/`, run `flatpak update`, re-installed Evolution and it keeps crashing.
I can't seem to find what's wrong.

I'm using i3-wm without a DM. I haven't pushed the update in `.zprofile` for `GNUPGHOME`, but everything else is up to date. I was hopping you could make it so that I could use `export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg` and follow the XDG standard, but that's a different issue.
This is my dotfiles repo: https://github.com/ispanos/dotfiles

**Comment by Sesivany** [comment]
This seems like [a bug in libsecret](https://gitlab.gnome.org/GNOME/libsecret/-/merge_requests/52) in the GNOME runtime.

**Comment by ispanos** [comment]
I tested it and it still crashes when it tries to authenticate. I don't know if its updated yet.

-----
In [org.gnome.Evolution.json](https://github.com/flathub/org.gnome.Evolution/blob/master/org.gnome.Evolution.json) -> finish-arg -> **"--filesystem=~/.gnupg:rw"**
Can the **~/.gnupg** be changed so that I can use a different GNUPGHOME?
i.e `export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg`

I ever since I created this issue, that line is commented out of my .profile (.zprofile), so that's not related to the crashes.

**Comment by yousefamar** [comment]
Have you managed to fix this? I get the same behaviour all the way up to the crash (it doesn't crash for me)

**Comment by Sesivany** [comment]
It should be fixed in the latest release, can you please verify if it's fixed for you?

**Comment by Sesivany** [comment]
We haven't seen this issue ever since, thus closing.
