### ISSUE TITLE
Printing dialog doesn't list printers from system

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Evolution#3]
When selecting File -> Print on a message, I am only presented with the options of "Print to File" and "Print to LPR".  Whereas for example other applications (eg gedit) I am able to see printers that are listed on the host.

# Evolution
![screenshot from 2018-10-03 20-22-12](https://user-images.githubusercontent.com/3669750/46433970-252ccb00-c74a-11e8-8da1-ad3db8de796e.png)

# gedit
![screenshot from 2018-10-03 20-23-30](https://user-images.githubusercontent.com/3669750/46433996-3b3a8b80-c74a-11e8-9f7b-646651d24bb6.png)

**Comment by Sesivany** [comment]
This is an issue with Evolution currently not using portals. Upstream is aware of it. Currently the only workaround I can think of is printing email into PDF and then print them from a PDF viewer.

**Comment by Sesivany** [comment]
Evolution is using WebKitGTK for printing and until it's fixed there, it won't be solved: https://bugs.webkit.org/show_bug.cgi?id=79226#c8

**Comment by OzzieIsaacs** [comment]
I'm having the same issue, but your suggested workaround isn't working for me, I don't see my real disk, only the virtual one(?):
My harddisk in the printing dialog on the "normal evolution":
![screenshot_orig](https://user-images.githubusercontent.com/6438895/73133436-d256e100-4028-11ea-836e-578a8420b00c.png)
My harddisk in the printing dialog on the "flatpak evolution":
![screenshot_2_1](https://user-images.githubusercontent.com/6438895/73133460-2792f280-4029-11ea-8ffa-5d71ea0329b2.png)
I tried to find the folders and files on my real harddisk, but I wasn't successfull. Where do I find the folders on my local drive?
I'm using Linux Mint 19.3, tested it with the shipped flatpak version, and now tried to update to the most recent version 1.6.1 (the evolution flatpak itself was installed with the old version 1.09 or so)

**Comment by vbatts** [comment]
> This is an issue with Evolution currently not using portals. Upstream is aware of it. Currently the only workaround I can think of is printing email into PDF and then print them from a PDF viewer.

When printing to PDF, the output is not in the portal filesystem either. Any help on this?

**Comment by TingPing** [comment]
> When printing to PDF, the output is not in the portal filesystem either. Any help on this?

You could save it to `~/.var/app/org.gnome.Evolution/data`.

Sidenote there is somebody working on WebKitGTK printing using the portal atm, so maybe that will happen by next release cycle.

**Comment by OzzieIsaacs** [comment]
Thanks for the feedback. It worked, but it's far from easy to use (you have to manually enter the path everytime you want to print an email) 
I'll wait for the hopefully coming change in WebKitGTK

**Comment by Sesivany** [comment]
This should be fixed now, closing.
