### ISSUE TITLE
Application icon in notifications not found/wrong

### ISSUE THREAD

**Issue by lightonflux** [flathub/org.gnome.Evolution#33]
Since the last update notifications on gnome 3.36 display the broken / not found replacement icon instead of the envelope icon in a notification.

**Comment by Sesivany** [comment]
I assume you're using Silverblue, aren't you?

**Comment by lightonflux** [comment]
No, Fedora Workstation with the flatpak from flathub.

**Comment by Sesivany** [comment]
This should be resolved with 3.42.1, closing.
