### ISSUE TITLE
GNUPGHOME environmental variable support

### ISSUE THREAD

**Issue by ispanos** [flathub/org.gnome.Evolution#34]
In [org.gnome.Evolution.json](https://github.com/flathub/org.gnome.Evolution/blob/master/org.gnome.Evolution.json) -> finish-arg -> **"--filesystem=~/.gnupg:rw"**
Can the **~/.gnupg** be changed so that I can use a different GNUPGHOME?
i.e `export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg`

That variable is set in `.profile`.

**Comment by Sesivany** [comment]
Flatpak doesn't take env variables as permissions, but I suppose adding "--filesystem=xdg-config/gnupg:rw" could also be a solution for your use case?

**Comment by ispanos** [comment]
> Flatpak doesn't take env variables as permissions, but I suppose adding "--filesystem=xdg-config/gnupg:rw" could also be a solution for your use case?

What does `xdg-config/` translate to?

**Comment by Sesivany** [comment]
It should be `$HOME/.config`.

**Comment by ispanos** [comment]
> It should be `$HOME/.config`.

I guess it would work. But where is `xdg-config` set to `$HOME/.config`? Isn't that some sort of enviromental variable?

**Comment by Sesivany** [comment]
Docs for it is here: https://specifications.freedesktop.org/basedir-spec/latest/
Most systemd distros set this in /etc/profile.d.

**Comment by ispanos** [comment]
> Docs for it is here: https://specifications.freedesktop.org/basedir-spec/latest/
> Most systemd distros set this in /etc/profile.d.

So, since Flatpak doesn't take env variables as permissions, this applies:

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

Anyway. It should be done in a way that doesn't break compatibility if someone has their `gnupg` in their home dir. But aslo work if someone manyally tried to make `gnupg`  XDG compliant. It's up to you.

**Comment by alexlarsson** [comment]
> So, since Flatpak doesn't take env variables as permissions, this applies:
> 
> > If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

Flatpak doesn't expand arbitrary env-vars in the permission string. However, it *does* use $XDG_CONFIG_HOME when finding the xdg config dir.

**Comment by Sesivany** [comment]
Shipped in 3.38.2 update. Closing.
