### ISSUE TITLE
After platform update expand/collapse buttons have changed colours

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Evolution#37]
I think after the recent update for`org.gnome.Platform//3.36` this has caused some buttons in the evolution message pane to regress their styling (even with Adwaita gtk and icon theme it looks odd). Before this looked perfect with arc-dark/papirus-dark or Adwaita.

Before

![evolution-attachment-before-update](https://user-images.githubusercontent.com/3669750/93131524-1f78e780-f6cc-11ea-8119-f60d4190dad9.png)

After

![evolution-attachment-after-update](https://user-images.githubusercontent.com/3669750/93131542-29024f80-f6cc-11ea-869e-3ffd9e47ccfe.png)
![evolution-addresses-after-update](https://user-images.githubusercontent.com/3669750/93131548-2c95d680-f6cc-11ea-9d1e-ef744255ec9d.png)

Not sure if this an application issue or runtime issue, so reported here.

Note that the following versions are being used

```
org.gnome.Platform//3.36
Commit: 5626f7387f5d7cdd792c9786a1f27d92b5cdd4eafa145c7e37abe36c4acbc61e
Parent: 939a3f4709d016eec987e3e51b98bd45c1c32ea9b626c60afc9e0b27ced7427a
Subject: Export org.gnome.Platform
Date: 2020-09-12 12:17:43 +0000

org.gnome.Evolution
Commit: 121b37ffc334619d19f2cf52995d2684d4a4f4964ca6bc6c495807c174529ac7
Parent: e0d7d67f8bdf8a956e3d514c9be9fe885d294dd490559ddd991174d17b770b57
Subject: Update to 3.36.5 (9e06da5f)
Date: 2020-08-07 12:25:35 +0000
```

**Comment by ahayzen** [comment]
I can confirm running with `flatpak run --runtime-commit=939a3f4709d016eec987e3e51b98bd45c1c32ea9b626c60afc9e0b27ced7427a org.gnome.Evolution` solves the issue. So definitely seems to be as a result of the runtime update.

**Comment by Sesivany** [comment]
It's because WebKitGTK no longer follows GTK themes for rendering buttons. We fully rely on WebKitGTK with this and Evolution is only tested with the light Adwaita theme. If you want to change the behavior, please open an issue with WebKitGTK.

**Comment by ahayzen** [comment]
OK thanks, it's kinda disappointing that Adwaita-dark isn't even supported by WebKitGTK, and I'm also surprised that the whole recipient list of the message is infact coming from a web view :-) I'll see if I can find where to report a bug for WebKitGTK ...
