### ISSUE TITLE
Use GNOME 3.30 Runtime

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Evolution#4]
The GNOME 3.30 runtime is now available. It'd be great to move to that if possible, since that's the version supported by the GNOME release team and it has better security support. Doing the absolutely simplest option of:

> flatpak run --runtime=org.gnome.Platform//3.30 org.gnome.Evolution

Fails to launch, with a nice:

> /app/bin/evolution: line 3: /app/libexec/evolution-data-server/evolution-dbus-session: No such file or directory

so it looks like a little bit of tweaking will be required.

**Comment by Sesivany** [comment]
Switching to 3.30 is in our plans. As you say it requires some tweaking and we'd like to focus on more urgent problems with Evo in Flatpak right now.

**Comment by Sesivany** [comment]
The updated flatpak (to the upstream version 3.30.3) is using the 3.30 runtime. Closing...
