### ISSUE TITLE
Error message with Evolution Flatpak installation

### ISSUE THREAD

**Issue by mochiballs** [flathub/org.gnome.Evolution#40]
Cannot install the Flatpak version. I am running Linux Mint 19.3 Cinnamon.

```
flatpak install flathub org.gnome.Evolution
Installing in system:
org.gnome.Evolution/x86_64/stable flathub 5f468bb437df
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: xdg-run/dconf, ~/.config/dconf:ro, ~/.gnupg
  dbus access: ca.desrt.dconf, org.freedesktop.Notifications, org.freedesktop.secrets, org.gnome.OnlineAccounts, org.gnome.keyring.SystemPrompter
Is this ok [y/n]: y
Installing: org.gnome.Evolution/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 592 B transferred in 0 secondsflatpak install: Non-prefixed filename org.gnome.Evolution.org.gnome.evolution.dataserver.Sources5.service in app org.gnome.Evolution, removing.

error: Failed to install org.gnome.Evolution/x86_64/stable: No such file or directory
```

**Comment by izahn** [comment]
I also have this problem on RHEL 7.5.

**Comment by ctfolmar** [comment]
I get the same error message

**Comment by schlauerlauer** [comment]
Same here on Ubuntu 18.04

**Comment by tkossak** [comment]
same for me on Linux Mint 19.2

**Comment by ctfolmar** [comment]
Apparently there is no solution for it.

**Comment by tkossak** [comment]
It's strange that official way of installing it doesn't work for over a month. Maybe this project is abandoned and we shouldn't use it anymore?

**Comment by ctfolmar** [comment]
It's starting to look like flathub has been abandoned.

**Comment by Sesivany** [comment]
This is an issue with an older version of Flatpak, see: https://github.com/flathub/org.gnome.Evolution/issues/39
Evolution developers can't really do much about this, so I'm closing it. If the issue persists, please report it to Flathub maintainers or Flatpak developers.
