### ISSUE TITLE
Please set X-DConf=migrate-path in manifest

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Evolution#42]
As dconf is now a keyfile backend and sandboxed from the host (apps that move to GNOME 3.38 runtime get this automatically), apps need to set the dconf migrate path (see the end of https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/ )

There are at least two use cases I have come across so far that this will help with
  * Migration of existing settings when user upgrade
  * If vendor overrides have been set in the hosts `/usr/share/glib-2.0/schemas` via `gschema.override` these default settings are then passed to the app in a sandboxed way.

I think this should just be adding `"--metadata=X-DConf=migrate-path=/org/gnome/evolution/"` to the manifest - see Calculator for an example https://github.com/flathub/org.gnome.Calculator/blob/master/org.gnome.Calculator.json#L14

**Comment by Sesivany** [comment]
Shipped in 3.38.2.

**Comment by mcrha** [comment]
Is it possible these migration causes settings lost on update of the app, as is filled in the https://github.com/flathub/org.gnome.Evolution/issues/179 ? Maybe there's a bug in the flatpak overriding user changes on update, I do not know, it's only this key which I can think of causing the trouble filled in the other issue.

**Comment by mcrha** [comment]
I just verified the migration with the settings from the host system runs only if the `~/.var/app/org.gnome.Evolution/config/glib-2.0/settings/keyfile` file does not exist. At least with flatpak-1.15.8.
