### ISSUE TITLE
After siwtch to Fedora 32: org.gnome.Evolution no longer interacts with gnome-keychain

### ISSUE THREAD

**Issue by r-cheologist** [flathub/org.gnome.Evolution#44]
Hi,
When running `flathub run org.gnome.evolution` on my setup freshly upgraded to Fedora 32, I need to provide all passwords constantly and if I do, the `CLI` remarks `Failed to store source credentials: user interaction failed` ... on Fedora 31 the identical setup worked ...

Any hints on where to start digging?

**Comment by r-cheologist** [comment]
... and org.gnome.seahorse.Application from flathub accesses the keychains ok ... what is going wrong for evolution?

**Comment by Sesivany** [comment]
We've observed something similar when we launched Evolution for the second time. Can you please make sure that no evolution processes from /app/ are running (ps ax | grep evolution) and then launch the app and see if it still doesn't work?

**Comment by Sesivany** [comment]
No follow-up on this issues from the reporter, closing.
