### ISSUE TITLE
Replace --socket=x11 with --socket=fallback-x11

### ISSUE THREAD

**Issue by mcrha** [flathub/org.gnome.Evolution#49]
The GNOME Software considers applications requiring x11 as unsafe. There's a way to declare it uses Wayland, but can use X11 as a fallback, on desktop environments where Wayland doesn't run.

More info here:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/770#note_1136536

Thus (non-applicable rough diff):
```diff
-           "--socket=x11",
+           "--socket=fallback-x11",
```

**Comment by Sesivany** [comment]
Done
