### ISSUE TITLE
Only uses Adwaita

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/org.gnome.Evolution#5]
Evolution seems to only use Adwaita, in contrast to other GTK3 apps installed in Flatpak, like Quod Libet, happily using Adapta installed in ~/.themes. Is it intended to only use Adwaita? Is there somewhere I should symlink ~/.themes to get it to pick up Adapta?

**Comment by TingPing** [comment]
Flatpaks don't generally have read access to `~/.themes`. That is fine though because you just need to set the global theme name and Flatpak downloads it: 

```
gsettings set org.gnome.desktop.interface gtk-theme 'Adapta'
flatpak update
```

**Comment by TiZ-EX1** [comment]
Hmm, my gsettings gtk-theme value was set incorrectly. I'm on XFCE (Xubuntu 18.04.1 specifically) and other apps were behaving, so I just kind of presumed that was handled. But fixing it didn't help. Since I'm on XFCE, I don't think that does anything. What did end up helping me though was updating and rebuilding Adapta in combination with adding an override to allow filesystem access to home.

Thanks for your guidance here.

**Comment by TingPing** [comment]
Ah yea, XFCE doesn't have an XSettings daemon so it expects applications to read `~/.config/gtk-3.0` which sandboxed applications cannot.
