### ISSUE TITLE
Desktop calendar integration through evolution-server doesn't work

### ISSUE THREAD

**Issue by jacobzimmermann** [flathub/org.gnome.Evolution#51]
Hi

The flatpak version of evolution doesn't synchronise its calendar with the desktop (e.g. gnome shell). That feature works when running the same release installed from a distro's repositories. I presume it's related to the flatpak confinement?

Best.
Jacob

**Comment by Sesivany** [comment]
Yes, this is intentional. Flatpaks can't rely on components in the underlying system, so we can't share the evolution-data-server. The workaround is to use online calendaring solution and sync via a server.
If you think there should be some local syncing between flatpak e-d-s and system e-d-s, file a request upstream.

**Comment by jacobzimmermann** [comment]
There should be definitely some local sync for at least three reasons
that I can think of:

1. The EDS calendar is a fundamental feature of the GNOME desktop. That
it doesn't work with flatpak apps (which are also pushed by GNOME) is
an arbitrary limitation that violates the Just Works principle.

2. Effectively forcing user to revert to some online sync for a
personal calendar is a VERY MAJOR problem at best (all the hassle
involved in setting it up) and a severe violation of the FOSS
philosophy at worst by requiring users to rely on a potentially
proprietary third-party with all the privacy issues it entails.

3. Unless I'm mistaken, an online sync would only work for a personal
calendar, not a work O365 calendar for example.

**Comment by Sesivany** [comment]
I see your point, but as I said this is a discussion for upstream. But frankly I don't see this happening since there have even been plans to remove evolution-data-server from GNOME Shell altogether. So even if flatpaked Evolution learns to sync locally it may have nothing on the host to sync with.
