### ISSUE TITLE
Generate release notes from the NEWS files since 3.42.2

### ISSUE THREAD

**Issue by mcrha** [flathub/org.gnome.Evolution#66]
The upcoming Evolution 3.42.2 contains some changes, which allow to generate appdata release notes from the NEWS files. It merges the information from the NEWS for the evolution-data-server, evolution and evolution-ews.

The attached [evo.patch](https://github.com/flathub/org.gnome.Evolution/files/7467115/evo.patch.txt) adds necessary bits to the manifest to do it.

**Comment by Sesivany** [comment]
Included.
