### ISSUE TITLE
Cannot send mail via postfix

### ISSUE THREAD

**Issue by fansari** [flathub/org.gnome.Evolution#7]
I installed Evolution via flatpak today on Fedora 29 Silverblue.

For sending mails I choose sendmail. But when I try to send an email there is an error message saying it could not execute /usr/sbin/sendmail.

The rpm based Evolution does not have this problem.

**Comment by Sesivany** [comment]
It's because apps in flatpaks run in their own namespace, they can't access tools on the host. I'm not sure if it would be wise to enable that access. Once you rely on host software, you no longer provide a fully distro-agnostic app format.

**Comment by fansari** [comment]
OK - there is an easy alternative. If you really want to loop your emails through your local postfix you can just use "::1:25" as mailserver.

**Comment by Sesivany** [comment]
Closing this one since we don't even show that option in UI any more if Evolution is runnning in flatpak.
