### ISSUE TITLE
Add evolution-rss plugin

### ISSUE THREAD

**Issue by 0none** [flathub/org.gnome.Evolution#72]
Would it be possible to add the evolution-rss plugin?
https://gitlab.gnome.org/GNOME/evolution-rss

**Comment by Sesivany** [comment]
It would certainly be possible. Let me experiment with it in the beta channel first. I'd rather provide it as an app extension because the plugin is not widely used and I don't want it to install for everyone.

**Comment by Sesivany** [comment]
Sorry to say this, but I have to close it as a wontfix. The way Evolution plugins are done is not compatible with how flatpak extensions work and I don't want to install all possible plugins out there and bloat the installation size for everyone when they're used by just a few. Plus evolution-rss is no longer maintained and the lead developer of Evolution is planning to replace it with a new solution.

**Comment by 0none** [comment]
That is quite understandable.
Thank you for your time!

**Comment by mcrha** [comment]
For what it's worth, the 3.45.1 contains a built-in RSS reader.
