### ISSUE TITLE
Help->About says "flatpak git"

### ISSUE THREAD

**Issue by mcrha** [flathub/org.gnome.Evolution#76]
The Flathub.org version used to identify itself in the Help->About as `3.x.y (by Flathub.org)`. This regressed recently and only `3.x.y (flatpak git)` is shown there.

Return back the `by Flathub.org`, please. It's here: https://github.com/flathub/org.gnome.Evolution/blob/master/org.gnome.Evolution.json#L363

**Comment by Sesivany** [comment]
This should be fixed in the current version.
