### ISSUE TITLE
Only English selectable for spell checking

### ISSUE THREAD

**Issue by llabusch93** [flathub/org.gnome.Evolution#79]
Hello,
in the Flatpak version there is only English available for the spell checking. Is there a way to install for instance also a German dictionary  into the flatpak container, so Evolution can spell check it as well?

**Comment by Sesivany** [comment]
Evolution flatpak doesn't ship dictionaries, it relies on the runtime for them. AFAIK there is no way for an app to request a specific locale. By default Flatpak installs the locale of the system language. If it's German, you should have a German spellchecking available in Evolution. If you use English as the system language, but want German for spellchecking, there are just workarounds: [you can set Flatpak to install locales of other languages by default](https://docs.flatpak.org/en/latest/flatpak-command-reference.html?highlight=extra-languages#flatpak-config) and I think there is a way to install a specific locale for runtimes, too.

**Comment by llabusch93** [comment]
Hello @Sesivany 

this did not work for me, but [this answer I gave myself on Reddit](https://www.reddit.com/r/flatpak/comments/sa297m/comment/htzs44n). Hope that helps other guys coming around here as well!
