### ISSUE TITLE
Imported S/MIME certificate is lost

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Evolution#8]
# What happened

  1. Opened Evolution flatpak, navigated to certificate preferences (Edit -> Preferences -> Certificates)
  2. Selected "Import"
  3. Chose a S/MIME certificate (.p12 file) and entered the key to unlock the certificate
  4. Certificate was successfully added to the panel and I was able to associate it with an email account
  5. Restarted Evolution
  6. Navigated to Certificates and noticed that it was now empty, under my email account it listed the correct name and id of the certificate for the signing key - but fails to find it if I try to use the certificate in an email.

# What I expected to happen

At step 6 for the certificate to still be imported and unlocked into Evolution.

**Comment by Sesivany** [comment]
This has been fixed upstream and will be shipped in 3.32.1.
