### ISSUE TITLE
After transition to Nvidia card/Nouveau (fedora-34): flatpak evolution fails to display messages with webkit error

### ISSUE THREAD

**Issue by r-cheologist** [flathub/org.gnome.Evolution#88]
I have evolution/flatpak setup in a fedora-34 based VM. Was running smoothly until I switched my laptop to using the Nvidia card/Nouveau rather than the integrated Intel one.

Now evolution will start, but fail to display any messages showing

1. in the GUI: `Something has gone wrong when displaying the message. A WebkitWebProcess crashed when displaying the message. You can try again by moving to another message and back. If the issue persists, please file a bug report in GNOME Gitlab.`

2. on the CLI (from which evolution was started with `flatpak run`):
   ```
   (WebKitWebProcess:188): Gdk-CRITICAL **: 23:13:29:416: gdk_atom_intern: assertion 'atom_name != NULL' failed
   libEGL warning: DRI2: failed to authenticate
   ```

What is going wrong here? I tried installing the Nouveau xorg drivers in the VM which didn't fix this, nor did adding `org.freedesktop.Platform.GL32.default` ...

**Comment by mcrha** [comment]
You should ask on the WebKitGTK side, this is out of the Evolution hands. I'd suggest to disable the hardware acceleration for this virtual machine, especially when it's used only for Evolution. You can also try to run Evolution from a terminal as:

```
 $ WEBKIT_DISABLE_COMPOSITING_MODE=1 flatpak run org.gnome.Evolution
```

whether it'll have any impact, but other than that there's not much else to be done on the Evolution side.

**Comment by r-cheologist** [comment]
Thank you for your input. 
I just switched the underlying OS image from `fedora-34` to `debian-11` ... and it magically works - thank god for virtualization! I'll ask  the `WebKitGTK` folks and close her for now.

**Comment by r-cheologist** [comment]
Here's the attempt at a follow up: https://bugs.webkit.org/show_bug.cgi?id=238445

**Comment by r-cheologist** [comment]
> ... You can also try to run Evolution from a terminal as:
> 
> ```
>  $ WEBKIT_DISABLE_COMPOSITING_MODE=1 flatpak run org.gnome.Evolution
> ```
> 
> whether it'll have any impact, but other than that there's not much else to be done on the Evolution side.

When returning to a `fedora-34`-base, this indeed makes the problem go away.
