### ISSUE TITLE
Attachments cannot be opened

### ISSUE THREAD

**Issue by mcrha** [flathub/org.gnome.Evolution#89]
Moving this from a downstream bug report:
https://gitlab.gnome.org/GNOME/evolution/-/issues/1850

Hi there,

since version 3.44, attachments can no longer be opened directly in Evolution. The attachments must be saved separately.

```
Evolution 3.44.0 Flatpack
Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia 
Kernel: 4.15.0-173-generic x86_64 bits: 64
```

Version 3.42.3 (Flatpak) is OK!

**Comment by Sesivany** [comment]
I can reproduce it on my machine as well. Not sure what could be the culprit of it. Evo 3.44 is even using the GNOME 41 runtime just like 3.42. Could be some regression in the runtime update.

**Comment by mcrha** [comment]
Okay, I gave this some time to debug this and this is the outcome:

* evolution changed where it saves temporary files. It's in the directory returned by `g_dir_make_tmp()`, which uses `g_get_tmp_dir()`, which means (usually) `/tmp` directory. It does use this directory under flatpak as well
* the file is saved into a subdirectory of this temporary directory and `g_app_info_launch_default_for_uri()` is called - this function returns success, no error message, even it did not succeed - I found there is a glib bug for it: https://gitlab.gnome.org/GNOME/glib/-/issues/2235
* the previous version of Evolution used its own tmp directory, under `~/.cache/evolution/tmp/`, which the `g_app_info_launch_default_for_uri()` is willing to pass to the system.

[This patch.txt](https://github.com/flathub/org.gnome.Evolution/files/8396627/evo.patch.txt) can be applied on top of the org.gnome.Evolution.json and it'll fix it (or better it'll workaround the bug on the glib side).

**Comment by Sesivany** [comment]
This should be fixed in the latest update, closing.
