### ISSUE TITLE
Cannot open PDF attachment

### ISSUE THREAD

**Issue by gatons** [flathub/org.gnome.Evolution#9]
![image](https://user-images.githubusercontent.com/6638922/55326999-c5617380-5491-11e9-9c3a-abfa47e2bc33.png)

Cannot open pdf attachments.

**Comment by Sesivany** [comment]
Do you have xdg-desktop-portal installed? Because Evolution's request to open a file is not translated outside the sandbox in your case. If xdg-desktop-portal is running Evolution hands the file over to the app that is supposed to open it just fine.

**Comment by gatons** [comment]
Yes, both packages - xdg-desktop-portal and xdg-desktop-portal-gtk are installed.

Debian Stretch, Flatpak 0.8.9

**Comment by gatons** [comment]
hi, that was problem with ancient Flatpak version. Have installed version 1.2.3-1 from Debian backports - problem solved. Thanks.
