### ISSUE TITLE
Icon theme looks odd

### ISSUE THREAD

**Issue by philn** [flathub/org.gnome.Evolution#95]
Is this the expected look and feel for Evolution?
![Screenshot from 2022-08-10 08-52-31](https://user-images.githubusercontent.com/34114/183910469-e787e815-d133-477d-9704-715888d25eeb.png)

**Comment by fansari** [comment]
Seems like this. Maybe this is a matter of taste.I admit I also thought that something might have gone wrong with the installation.

I have inow nstalled the RPM version because on my system the flatpak version does not send mails but it is hanging.

The RPM version of 3.44.4 looks the same.

**Comment by Sesivany** [comment]
It is intended look. Flatpak has nothing to do with it. If you have a problem with it, please file a bug in the Evolution issue tracker. Closing.
